# Template to use with AWS Elasticsearch service with public access
# Define user using fine-grained

version: "3"

services:
    sync:
        image: geronimosearch/mysql-sync
        environment:
            - MYSQL_USERNAME=mysql_user
            - MYSQL_PASSWORD=mysql_password
            - MYSQL_HOST=host.docker.internal
            - MYSQL_DB=schema_name
            - MYSQL_TABLE=table_name
            - ES_HOST=https://my-elasticsearch-host
            - ES_INDEX=index_name
            - ES_USERNAME=es_user
            - ES_PASSWORD=es_user_password
            - ES_SERVICE=aws
            - ES_REGION=eu-central-1
        depends_on: 
            - rabbitmq
    rabbitmq:
        image: rabbitmq:3.8.2
        ports: 
            - 5672:5672

